# Generated by Django 5.1.7 on 2025-03-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionPriorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_cliente', models.CharField(max_length=11, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('ruta', models.CharField(max_length=50)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
